### ISSUE TITLE
Enable mapping a device to a mark, using a QR code

### ISSUE THREAD

**Issue by aksajhfduwafe** [aksajhfduwafe/bugzilla-to-github-issues-test#2688]
| Field | Value |
|---|---|
| **Reporter** | @axeluhl |
| **Assignee** | @axeluhl |
| **Product** | Sailing Race Analytics |
| **Component** | Smartphone Tracking |
| **Version** | unspecified |
| **Hardware** | All |
| **OS** | All |
| **Severity** | enhancement |
| **Priority** | P1 |
| **CC (unmapped)** | Bennet Brunsen (`brunsen@ubilabs.net`), Jan Broß (`jan.bross@arcor.de`), Marcus Baur (`marcus.baur@sapsailing.com`), Mark Angell (`mark@markangell.com`), Samuel Oey (`oey@ubilabs.net`), Raimund Wege (`wege@ubilabs.net`) |
| **Created** | 2015-03-05T13:01:19Z |
| **Original Bug** | [Bug 2688](https://bugzilla.sapsailing.com/bugzilla/show_bug.cgi?id=2688) |

---

When a user wants to assign a device to a mark for some time frame, this shall be possible. Could this be a slight variation of the tracking app where instead of a competitor a mark is associated to the device?

**Comment by aksajhfduwafe** [comment]
**Samuel Oey (`oey@ubilabs.net`)** commented:

@Axel Uhl:
- [ ] Please provide the QR-Code / Deeplink for a buoy tracking
@Bennet Brunsen:
- [ ] Handle the buoy tracking checkins the same as for competitors and show them in the same list
- [ ] Create a simple "buoy  fragment" used instead of "regatta fragment" for buoy trackings without the following features:
-- [ ] button to event
-- [ ] button to leaderboard
-- [ ] team image upload
- [ ] Create a simplified "buoy tracking screen" after the user started a buoy tracking only having a "stop tracking" button and everything above the existing view pager.

**Comment by aksajhfduwafe** [comment]
*@axeluhl* changed status from **ASSIGNED** to **RESOLVED** (FIXED)
